-- CodeFlow ELO Supabase Schema
-- Run this in the Supabase SQL editor.
-- Assuming auth.users and a basic public.profiles table exist, or we can create profiles:

-- 1. PROFILES (Extended with ELO)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  elo_rating integer not null default 800, -- Initial ELO for beginners (can be set to 1200 via logic)
  created_at timestamptz not null default now()
);

-- RLS for profiles
alter table public.profiles enable row level security;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- 2. TOPICS & SUBTOPICS
create table if not exists public.topics (
  id uuid primary key default gen_random_uuid(),
  name text not null, -- e.g., 'Two Pointers', 'Sliding Window', 'Binary Search'
  created_at timestamptz not null default now()
);

create table if not exists public.sub_topics (
  id uuid primary key default gen_random_uuid(),
  topic_id uuid not null references public.topics(id) on delete cascade,
  name text not null, -- e.g., 'Opposite Ends', 'Fixed Size'
  created_at timestamptz not null default now()
);

-- 3. PROBLEMS
create table if not exists public.problems (
  id uuid primary key default gen_random_uuid(),
  sub_topic_id uuid not null references public.sub_topics(id) on delete cascade,
  title text not null,
  markdown_description text not null,
  difficulty_elo integer not null default 800, -- Starting problem ELO
  constraints text not null,
  sample_io jsonb not null default '[]'::jsonb, -- [{input: "...", output: "...", explanation: "..."}]
  hidden_test_cases jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- Note: Problems, Topics, and SubTopics are usually public read-only
alter table public.topics enable row level security;
create policy "Topics are viewable by everyone" on public.topics for select using (true);

alter table public.sub_topics enable row level security;
create policy "Subtopics are viewable by everyone" on public.sub_topics for select using (true);

alter table public.problems enable row level security;
create policy "Problems are viewable by everyone" on public.problems for select using (true);

-- 4. QUIZZES (AI Gatekeeper)
create table if not exists public.quizzes (
  id uuid primary key default gen_random_uuid(),
  sub_topic_id uuid not null references public.sub_topics(id) on delete cascade,
  cheat_sheet text not null,
  questions jsonb not null default '[]'::jsonb, -- Array of 5 questions generated by Gemini
  created_at timestamptz not null default now()
);

alter table public.quizzes enable row level security;
create policy "Quizzes are viewable by everyone" on public.quizzes for select using (true);

-- 5. USER PROGRESS & GATEKEEPER LOCKS
create table if not exists public.user_quiz_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  sub_topic_id uuid not null references public.sub_topics(id) on delete cascade,
  score integer not null default 0,
  passed boolean not null default false, -- Requires 4/5
  created_at timestamptz not null default now(),
  unique(user_id, sub_topic_id)
);

alter table public.user_quiz_progress enable row level security;
create policy "Users can view own quiz progress" on public.user_quiz_progress for select using (auth.uid() = user_id);
create policy "Users can insert own quiz progress" on public.user_quiz_progress for insert with check (auth.uid() = user_id);
create policy "Users can update own quiz progress" on public.user_quiz_progress for update using (auth.uid() = user_id);

-- 6. REAL-TIME AI OBSERVER: MISTAKE HISTORY
create table if not exists public.user_mistake_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  problem_id uuid not null references public.problems(id) on delete cascade,
  code text not null,
  mistake_type text not null, -- E.g., 'off-by-one', 'infinite loop'
  context text, -- Additional notes from AI
  created_at timestamptz not null default now()
);

alter table public.user_mistake_history enable row level security;
create policy "Users can view own mistakes" on public.user_mistake_history for select using (auth.uid() = user_id);
create policy "Users can insert own mistakes" on public.user_mistake_history for insert with check (auth.uid() = user_id);
