-- Bharat DSA Yatra — Supabase schema (profiles + attempts)
-- Run in Supabase SQL editor (or via migrations).

-- Extensions
create extension if not exists "pgcrypto";

-- Profiles: 1:1 with auth.users
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  college text not null default '',
  branch text not null default '',
  graduation_year integer,
  xp integer not null default 0,
  readiness_score integer not null default 0,
  created_at timestamptz not null default now()
);

-- Attempts: history of submissions/runs
create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  node_id text not null,
  code text not null default '',
  result jsonb not null default '{}'::jsonb,
  score integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists attempts_user_id_created_at_idx
  on public.attempts (user_id, created_at desc);

-- Trigger: auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, college, branch, graduation_year)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'college', ''),
    coalesce(new.raw_user_meta_data->>'branch', ''),
    nullif(new.raw_user_meta_data->>'graduation_year', '')::integer
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RLS
alter table public.profiles enable row level security;
alter table public.attempts enable row level security;

-- Profiles policies
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Attempts policies
drop policy if exists "attempts_select_own" on public.attempts;
create policy "attempts_select_own"
  on public.attempts
  for select
  using (auth.uid() = user_id);

drop policy if exists "attempts_insert_own" on public.attempts;
create policy "attempts_insert_own"
  on public.attempts
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "attempts_update_own" on public.attempts;
create policy "attempts_update_own"
  on public.attempts
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "attempts_delete_own" on public.attempts;
create policy "attempts_delete_own"
  on public.attempts
  for delete
  using (auth.uid() = user_id);

